; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=OOP projektas
AppVersion=3.0
WizardStyle=modern
DefaultDirName={autopf}\OOP projektas
DefaultGroupName=OOP projektas
UninstallDisplayIcon={app}\1.5v_custom.exe
Compression=lzma2
SolidCompression=yes
OutputDir=userdocs:IDK

[Files]
Source: ".\build\1.5v_custom.exe"; DestDir: "{app}"
Source: ".\build\10000.txt"; DestDir: "{app}"
Source: ".\build\100000.txt"; DestDir: "{app}"

[Icons]
Name: "{group}\OOP projektas"; Filename: "{app}\1.5v_custom.exe"